//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JacobBabiksBrowser.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRand", ReplyAction="http://tempuri.org/IService1/GetRandResponse")]
        int GetRand();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRand", ReplyAction="http://tempuri.org/IService1/GetRandResponse")]
        System.Threading.Tasks.Task<int> GetRandAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Compare", ReplyAction="http://tempuri.org/IService1/CompareResponse")]
        string Compare(int guess, int random);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Compare", ReplyAction="http://tempuri.org/IService1/CompareResponse")]
        System.Threading.Tasks.Task<string> CompareAsync(int guess, int random);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : JacobBabiksBrowser.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<JacobBabiksBrowser.ServiceReference1.IService1>, JacobBabiksBrowser.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetRand() {
            return base.Channel.GetRand();
        }
        
        public System.Threading.Tasks.Task<int> GetRandAsync() {
            return base.Channel.GetRandAsync();
        }
        
        public string Compare(int guess, int random) {
            return base.Channel.Compare(guess, random);
        }
        
        public System.Threading.Tasks.Task<string> CompareAsync(int guess, int random) {
            return base.Channel.CompareAsync(guess, random);
        }
    }
}
